/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as EquipeRouteImport } from './routes/equipe'
import { Route as LojaRouteImport } from './routes/loja'
import { Route as LojaFisicaRouteImport } from './routes/loja-fisica'
import { Route as PdvRouteImport } from './routes/pdv'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as RelatoriosRouteImport } from './routes/relatorios'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaRoute = LojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaFisicaRoute = LojaFisicaRouteImport.update({
  id: '/loja-fisica',
  path: '/loja-fisica',
  getParentRoute: () => rootRouteImport,
} as any)
const PdvRoute = PdvRouteImport.update({
  id: '/pdv',
  path: '/pdv',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/delivery': typeof DeliveryRoute
  '/equipe': typeof EquipeRoute
  '/loja': typeof LojaRoute
  '/loja-fisica': typeof LojaFisicaRoute
  '/pdv': typeof PdvRoute
  '/produtos': typeof ProdutosRoute
  '/relatorios': typeof RelatoriosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/delivery': typeof DeliveryRoute
  '/equipe': typeof EquipeRoute
  '/loja': typeof LojaRoute
  '/loja-fisica': typeof LojaFisicaRoute
  '/pdv': typeof PdvRoute
  '/produtos': typeof ProdutosRoute
  '/relatorios': typeof RelatoriosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/delivery': typeof DeliveryRoute
  '/equipe': typeof EquipeRoute
  '/loja': typeof LojaRoute
  '/loja-fisica': typeof LojaFisicaRoute
  '/pdv': typeof PdvRoute
  '/produtos': typeof ProdutosRoute
  '/relatorios': typeof RelatoriosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/configuracoes'
    | '/dashboard'
    | '/delivery'
    | '/equipe'
    | '/loja'
    | '/loja-fisica'
    | '/pdv'
    | '/produtos'
    | '/relatorios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/configuracoes'
    | '/dashboard'
    | '/delivery'
    | '/equipe'
    | '/loja'
    | '/loja-fisica'
    | '/pdv'
    | '/produtos'
    | '/relatorios'
  id:
    | '__root__'
    | '/'
    | '/configuracoes'
    | '/dashboard'
    | '/delivery'
    | '/equipe'
    | '/loja'
    | '/loja-fisica'
    | '/pdv'
    | '/produtos'
    | '/relatorios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  DashboardRoute: typeof DashboardRoute
  DeliveryRoute: typeof DeliveryRoute
  EquipeRoute: typeof EquipeRoute
  LojaRoute: typeof LojaRoute
  LojaFisicaRoute: typeof LojaFisicaRoute
  PdvRoute: typeof PdvRoute
  ProdutosRoute: typeof ProdutosRoute
  RelatoriosRoute: typeof RelatoriosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja': {
      id: '/loja'
      path: '/loja'
      fullPath: '/loja'
      preLoaderRoute: typeof LojaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja-fisica': {
      id: '/loja-fisica'
      path: '/loja-fisica'
      fullPath: '/loja-fisica'
      preLoaderRoute: typeof LojaFisicaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdv': {
      id: '/pdv'
      path: '/pdv'
      fullPath: '/pdv'
      preLoaderRoute: typeof PdvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  DashboardRoute: DashboardRoute,
  DeliveryRoute: DeliveryRoute,
  EquipeRoute: EquipeRoute,
  LojaRoute: LojaRoute,
  LojaFisicaRoute: LojaFisicaRoute,
  PdvRoute: PdvRoute,
  ProdutosRoute: ProdutosRoute,
  RelatoriosRoute: RelatoriosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
